name = "cloudflaretest"
main = "src/index.js"
compatibility_date = "2026-02-11"

[[kv_namespaces]]
binding = "IntegrationConfigKV"
id = "8e00e10eb3ab405591634680ef25c74e" # ← ここにCloudflareで作ったKVのIDを貼る

[vars]
CUSTOMER_ID = "YOUR_ID"
SECRET_KEY = "YOUR_SECRET"
API_KEY = "YOUR_API_KEY"
